### PR TITLE
Updates to Vdrilling Publishers

### PR DESCRIPTION
**Pull request by nnagururu**
Voxels removed publisher now publishes proper color, and sim time moved to header.

Drill burr sizes halved, because 2mm, 4mm and 6mm are outside diameters not radii, as was previously implemented.

Drill burr size change publisher created.

### CODE REVIEW

**Comment by mli0603** [comment]
@nnagururu I think the drill size is not recorded?

**Comment by nnagururu** [comment]
1. Sorry, I completely forgot to add a subscriber in the recording script
2. Can do
Will have these done over the weekend

**Comment by mli0603** [comment]
@nnagururu I fixed the conversion factor hard-coding problem by reading the nrrd header (extracted from the nrrd you sent)

The volume resolution is not yet recorded because that depends on the command when launching. This is very tricky to record. Let's skip that for now.

**Comment by adnanmunawar** [comment]
The new commit in AMBF [c654ff49a7051549ccc1568a8ceae12505c9117a](https://github.com/WPI-AIM/ambf/commit/c654ff49a7051549ccc1568a8ceae12505c9117a) should allow us to query the volume's dimensions, voxel count and resolution using these three methods:

```cpp
m_volumeObject->getDimensions();
m_volumeObject->getVoxelCount();
m_volumeObject->getResolution();
```

**Comment by nnagururu** [comment]
Awesome, thanks Max and Adnan. I'll fix the data record script and write a subscriber for resolution and dimensions

**Comment by nnagururu** [comment]
burr_changes added to recording script, and colors converted from RGB float to RGB int

**Pull request merged**
