### PR TITLE
Hiding the stereo and depth camera to save computation

### PR DESCRIPTION
**Pull request by adnanmunawar**
Newer features in AMBF allow for the hiding of a camera and allow for its video or depth to be published. This saves a rendering pass and computational resources.

### CODE REVIEW

**Comment by nnagururu** [comment]
Looks good, thanks adnan! GPU usage went down from 54% to 38%. Data seems to still be recorded properly. Minor minor bug: pressing [f] (full-screen command) opens up all 4 windows (increasing usage to 4-5%), don't think that is a major problem tho

**Comment by adnanmunawar** [comment]
Thanks for the review Nimesh and pointing out the break in logic when you hit Fullscreen. This is coming from AMBF and should be easily fixed. The reduced GPU load is refreshing.

**Comment by adnanmunawar** [comment]
The new [commit](https://github.com/WPI-AIM/ambf/commit/017513e70779863660277a1256a74e88c62f835f) in AMBF should fix the issue when making the main window fullscreen. Please remember to update AMBF to the latest commit and recompile this plugin.

**Comment by nnagururu** [comment]
Looks good!

**Pull request merged**
